/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.CanvasEvent;

/**
 *
 * @author Caroline
 */
public class ClientGUI extends javax.swing.JFrame {
   
      //2D array för data til JTable (Tablemodel)
   private Object[][] data;
   private DefaultTableModel tblModel;

   /**
    * Creates new form ClientGUI
    */
   public ClientGUI() {
      initComponents();
   }
   
   private void loadEventsToJTable(CanvasEvent[] canvasEventsArray) {
      
      //Specifiera storlek på en annan array (kallad data) som används för att föra över datat till min JTable sen.
      int rows = canvasEventsArray.length;
      data = new Object[rows][4];
      int row = 0;
      for(CanvasEvent canvasEvent : canvasEventsArray) {
         //test
//         System.out.println(canvasEvent.getTitle() + canvasEvent.getLocationName() + canvasEvent.getLocationAddress() + canvasEvent.getDescription());
         //Ladda JTable
         data[row][0] = canvasEvent.getTitle();
         data[row][1] = canvasEvent.getLocationName();
         data[row][2] = canvasEvent.getLocationAddress();
         data[row][3] = canvasEvent.getDescription();
      }
      initTable();
   }
   
   //Relaterar arrayen data till JTable(tblCalendarEvents) som visar upp innehållet   
   private void initTable() {
      
      String[] columnNames = {"Title", "Location", "Address", "Details"};
      tblModel = new DefaultTableModel(this.data, columnNames);
      tblCalendarEvents.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
      tblCalendarEvents.setModel(tblModel);
      tblCalendarEvents.getColumnModel().getColumn(0).setPreferredWidth(10);
      tblCalendarEvents.getColumnModel().getColumn(1).setPreferredWidth(10);
      tblCalendarEvents.getColumnModel().getColumn(2).setPreferredWidth(10);
      tblCalendarEvents.getColumnModel().getColumn(3).setPreferredWidth(20);
      tblCalendarEvents.setShowGrid(true);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      tblCalendarEvents = new javax.swing.JTable();
      btnGetSchedule = new javax.swing.JButton();
      btnEditEvent = new javax.swing.JButton();
      btnLoadToCanvas = new javax.swing.JButton();
      jTextField1 = new javax.swing.JTextField();
      jTextField2 = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      lblCourseName = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      tblCalendarEvents.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
         },
         new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
         }
      ));
      jScrollPane1.setViewportView(tblCalendarEvents);

      btnGetSchedule.setText("Get schedule");

      btnEditEvent.setText("Edit selected event");

      btnLoadToCanvas.setText("Load schedule to Canvas");

      jTextField1.setForeground(new java.awt.Color(153, 153, 153));
      jTextField1.setText("ex D0031N");

      jTextField2.setForeground(new java.awt.Color(153, 153, 153));
      jTextField2.setText("ex 2019-09-02");

      jLabel1.setText("Course code:");

      jLabel2.setText("Sart date:");

      lblCourseName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      lblCourseName.setText("Course:");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(lblCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel1)
                     .addComponent(jLabel2))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField1)
                     .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))))
            .addGap(42, 42, 42)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnLoadToCanvas)
               .addComponent(btnEditEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnGetSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(23, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(28, 28, 28)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnGetSchedule)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel1))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel2))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
            .addComponent(lblCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addContainerGap())
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(btnEditEvent)
                  .addGap(148, 148, 148)
                  .addComponent(btnLoadToCanvas)
                  .addGap(25, 25, 25))))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new ClientGUI().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnEditEvent;
   private javax.swing.JButton btnGetSchedule;
   private javax.swing.JButton btnLoadToCanvas;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JTextField jTextField2;
   private javax.swing.JLabel lblCourseName;
   private javax.swing.JTable tblCalendarEvents;
   // End of variables declaration//GEN-END:variables
}
